version: '3.8'

services:
  ocrscan-frontend:
    container_name: ocrscan-frontend
    build: ./OCRScan.Frontend
    restart: always
#    env_file: ./OCRScan.Backend/.env
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules

  ocrscan-backend:
    container_name: ocrscan-backend
    build: ./OCRScan.Backend
    restart: always
    env_file: ./OCRScan.Backend/.env
    ports:
      - 5555:5555
    depends_on:
      - ocrscan-db

  ocrscan-db:
    container_name: ocrscan-db
    image: postgres:latest
    env_file:
      - ./OCRScan.Backend/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    
  nginx:
    depends_on:
      - ocrscan-frontend
      - ocrscan-backend
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      
volumes:
  pgdata:
